### ISSUE TITLE
The 'Place Order' event is not working.

### ISSUE THREAD

**Issue by memeq1** [Synerise/synerise-for-woocommerce#13]
hi, the order_placed event not working in 1.05.

`2023-08-08T14:27:08+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to Synerise\Integration\Service\Client_Service::prepare_client_params_from_order() must be an instance of WC_Order, null given, called in /var/www/app/plugins/synerise-for-woocommerce/src/Event/class-event-order-placed.php on line 33 and defined in /var/www//app/plugins/synerise-for-woocommerce/src/Service/class-client-service.php:42
Stack trace:
#0 /var/www/app/plugins/synerise-for-woocommerce/src/Event/class-event-order-placed.php(33): Synerise\Integration\Service\Client_Service::prepare_client_params_from_order()
#1 /var/www/wp/wp-includes/class-wp-hook.php(310): Synerise\Integration\Event\Event_Order_Placed->execute()
#2 /var/www/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /var/www/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/app/plug w /var/www/app/plugins/synerise-for-woocommerce/src/Service/class-client-service.php w linii 42`

Missing variable $order

Posible fix: add $order = wc_get_order($order_id)

https://github.com/Synerise/synerise-for-woocommerce/blob/344d99f4f369ed2b3e61376bd15c856ef57c7410/src/Event/class-event-order-placed.php#L23-L33

**Comment by kamilkanik** [comment]
Thank you for your help @memeq1.
In the next few days, a new release with bug fixes will be published.
