### ISSUE TITLE
Versioning and tags?

### ISSUE THREAD

**Issue by szpak** [Synerise/synerise-for-woocommerce#5]
We use `composer` to get your plugin (currently from "master"). To make our CI builds slightly more reproducible, it would be useful to introduce some versioning in synerise-for-woocommerce and tag each version (for people who prefer not to discover regression after unexpected upstream changes - just in general, I don't refer to synerise-for-woocommerce in particular). WDYT?

**Comment by kamilkanik** [comment]
You are right @szpak . I added first release and tag.
From now on, we will keep an eye on it.

**Comment by szpak** [comment]
Thanks @kamilkanik!
