### ISSUE TITLE
get_woocommerce_term_meta throws deprecated notice

### ISSUE THREAD

**Issue by memeq1** [Synerise/synerise-for-woocommerce#8]
With WP_DEBUG enabled, i have the following PHP Notice 

`Notice: get_woocommerce_term_meta is deprecated since version 3.6! Use get_term_meta instead.`

https://github.com/Synerise/synerise-for-woocommerce/blob/4efdeb8a4b45156885f2a7128a18300d286c238a/src/Service/class-open-graph-service.php#L40

**Comment by kamilkanik** [comment]
@memeq1 thank you for sharing this information. I have verified that the function get_term_meta() was introduced in WordPress version 4.4.0. Since we are supporting WordPress from version 4.7, I will replace this function and make the necessary adjustments.
