### ISSUE TITLE
support php8.1

### ISSUE THREAD

**Issue by memeq1** [Synerise/synerise-for-woocommerce#9]
Plugin support php 8.1 ? I have many notices like 

`[06-Jun-2023 13:57:29 UTC] PHP Deprecated:  Return type of Synerise\DataManagement\Model\InlineResponse2003::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in app/plugins/synerise-for-woocommerce/lib/api-data-management/Model/InlineResponse2003.php on line 229
`

**Comment by hellward** [comment]
Thank you for your report. Both issues got fixed in the latest release.
